### PR TITLE
Use the HTTPS endpoint

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Comment by sprice** [comment]
Tests failed. They might be out of date or it could be something else. I'll look into this asap and get this merged in.

**Comment by jpmckinney** [comment]
It's an npm build error, not a failed test.

**Comment by sprice** [comment]
@jpmckinney sorry this took so long

**Comment by sprice** [comment]
@jpmckinney package has been updated https://www.npmjs.com/package/represent

**Comment by jpmckinney** [comment]
Thanks!

**Pull request merged**
